spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://192.168.178.69:3306/3DDrucker-dev
    username: root
    password: Password1
    initialization-mode: always
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  #      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplykenosserver@gmail.com
    password: lwiwfysadgmfgzds
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true